/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Import from OpenAPI file
         * @description
         *     Upload your OpenAPI (previously known as Swagger) specification.
         *     Versions 2, 3, and 3.1 are supported. Both YAML and JSON formats are supported.
         *
         */
        put: operations["importActionsFromOpenAapiSpec"];
        post?: never;
        /**
         * Delete all actions
         * @description Delete all actions. This operation is safe only when you can re-import all the actions from an OpenAPI spec. Any actions created manually from the dashboard will be deleted.
         */
        delete: operations["deleteAllActions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List contacts */
        get: operations["listContacts"];
        put?: never;
        /**
         * Create a contact
         * @description Create a new contact
         */
        post: operations["saveContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a contact */
        delete: operations["deleteContact"];
        options?: never;
        head?: never;
        /** Update a contact */
        patch: operations["updateContact"];
        trace?: never;
    };
    "/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send emails
         * @description
         *     Send emails to multiple contacts, possibly with a time delay.
         *
         *     To send emails using the API, you must first verify the domain you want to
         *     send emails from. You can add and verify custom domains in the settings.
         *
         */
        post: operations["sendEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AI phone agents */
        get: operations["listPhoneNumbers"];
        put?: never;
        /**
         * Create an AI phone agent
         * @description
         *       Create an AI phone agent. This phone number can be used to receive and make phone calls. For now, this API only supports US phone numbers. Email mo@open.cx for other countries.
         *
         */
        post: operations["createPhoneAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phone/{phone_agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an AI phone agent */
        delete: operations["deletePhoneNumber"];
        options?: never;
        head?: never;
        /** Update an AI phone agent */
        patch: operations["updatePhoneAgent"];
        trace?: never;
    };
    "/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chat sessions */
        get: operations["listChatSessions"];
        put?: never;
        /** Create a chat session */
        post: operations["createChatSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a chat session */
        get: operations["getChatSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a chat session */
        patch: operations["updateChatSession"];
        trace?: never;
    };
    "/chat/sessions/{session_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a message */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chat session history */
        get: operations["listChatHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sequences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a sequence */
        post: operations["createSequence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sequences/{sequence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a sequence */
        get: operations["getSequence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a sequence */
        patch: operations["updateSequence"];
        trace?: never;
    };
    "/sequences/{sequence_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Start a sequence */
        put: operations["startSequence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sequences/{sequence_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cancel a sequence */
        put: operations["cancelSequence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sequences/{sequence_id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add contacts to a continuous sequence
         * @description
         *     Add contacts to a continuous sequence (`is_continuous` property of the sequence must be `true`).
         *     Contacts will *not* be added to the sequence if the sequence's `filter` does not apply to the contact.
         *
         *     Any contacts added will automatically be added to contacts if they don't already exist.
         *
         */
        post: operations["addContactsToSequence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widget/authenticate-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description authenticate the contacts */
        post: operations["authenticateWidgetUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddContactsToSequenceInput: {
            contacts: ({
                /** Format: uuid */
                id: string;
            } | {
                /** Format: email */
                email: string;
            } | {
                phone_number: string;
            })[];
        };
        AddContactsToSequenceOutput: {
            /** Format: uuid */
            run_id: string;
        };
        AuthenticateUserPayloadDto: {
            /**
             * Format: email
             * @description The email of the user to authenticate
             * @example jhon@example.com
             */
            email: string;
            /**
             * @description The name of the user to authenticate
             * @example John Doe
             */
            name?: string;
            /**
             * @description The URL of the user's avatar
             * @example https://example.com/avatar.png
             */
            avatar_url?: string | null;
            /**
             * @description contact's phone number including the conutry code
             * @example +1234567890
             */
            phone?: string;
            /**
             * @description Custom data
             * @example {
             *       "customKey": "customValue"
             *     }
             */
            customData?: {
                [key: string]: string | number | boolean;
            };
        };
        ChatMessageSender: {
            /** @enum {string} */
            type: "contact";
        } | {
            /** @enum {string} */
            type: "ai";
        } | {
            /** @enum {string} */
            type: "human_agent";
        };
        Contact: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string | null;
            phone_number: string | null;
            name: string | null;
            custom_data: {
                [key: string]: string;
            } | null;
        };
        ContactInput: {
            /** Format: email */
            email?: string;
            phone?: string;
            name?: string;
            custom_data?: {
                [key: string]: string;
            };
        };
        ContactsAffectedBySequenceFilter: {
            /** @enum {string} */
            type: "contacts_affected_by_sequence";
            sequence_id: string;
        };
        ContactsCreatedAtFilter: {
            /** @enum {string} */
            type: "contacts_created_at_between";
            /**
             * DateTime
             * Format: date-time
             * @description ISO 8601 date-time string
             */
            after?: string | null;
            /**
             * DateTime
             * Format: date-time
             * @description ISO 8601 date-time string
             */
            before?: string | null;
        };
        ContactsEmailDomainNameFilter: {
            /** @enum {string} */
            type: "contacts_email_domain_name_in";
            domain_name_in: string[];
        };
        ContactsFilter: components["schemas"]["ContactsIdsFilter"] | components["schemas"]["ContactsCreatedAtFilter"] | components["schemas"]["ContactsEmailDomainNameFilter"] | components["schemas"]["ContactsAffectedBySequenceFilter"];
        ContactsIdsFilter: {
            /** @enum {string} */
            type: "contact_id_in";
            contact_ids: string[];
        };
        /** @example {} */
        CreateChatSessionInput: {
            /** Format: uuid */
            contact_id?: string;
            /** @default {
             *       "type": "api"
             *     } */
            channel: {
                /**
                 * ChatSessionChannelType
                 * @enum {string}
                 */
                type: "web" | "email" | "phone_voice" | "slack" | "sms" | "whatsapp" | "api" | "web_voice";
            };
        };
        CreateChatSessionOutput: {
            /**
             * Format: uuid
             * @description ID of the created session.
             */
            id: string;
        };
        CreatePhoneAgentDto: {
            /** @description The name of the AI phone agent */
            name: string;
            /**
             * @default inbound
             * @enum {string}
             */
            type: "inbound" | "outbound";
            /** @description The language the AI phone agent should mainly speak in */
            language?: string | null;
            /** @description The accent the AI phone agent should mainly speak in */
            accent?: string | null;
            /** @description The phone number of the human agent to hand off the call to */
            handoff_phone_number?: string | null;
            /**
             * @description Whether the agent can be interrupted or not
             * @default true
             */
            interruptible: boolean;
            /** @description A list of action ids the AI phone agent has access to. A `null` value means all actions. An empty list means no actions */
            actionIds?: string[] | null;
            /** @description A list of instructions */
            instructions?: string[] | null;
            /** @description A list of fields to collect data about */
            data_collection_fields?: string[] | null;
            /** @description The webhook url to send the collected data to */
            data_collection_webhook_url?: string | null;
            /**
             * @description The AI model of the agent. This cannot be changed after creation
             * @default oppie-vox
             * @enum {string}
             */
            model: "oppie-vox" | "oppie-vox-turbo" | "oppie-vox-2";
            /** @description The first message the AI phone agent should say */
            first_message?: string | null;
            /** @description The voice id */
            voice_id?: string | null;
            flow: {
                /** @enum {string} */
                type: "root" | "condition" | "action";
                content: string;
                children: {
                    /** @enum {string} */
                    type: "root" | "condition" | "action";
                    content: string;
                    children: {
                        /** @enum {string} */
                        type: "root" | "condition" | "action";
                        content: string;
                        children: unknown[];
                    }[];
                }[];
            } | null;
            /** @description Whether the AI phone agent should use the organization's knowledgebase */
            use_org_knowledgebase?: boolean | null;
        };
        /** @example {
         *       "steps": [
         *         {
         *           "action": {
         *             "type": "send_emails",
         *             "data": {
         *               "from_email": "no-reply@hello.opencopilot.so",
         *               "email_body": "Hello!",
         *               "email_sender_name": "OpenCX Team",
         *               "email_subject": "Welcome to OpenCX!",
         *               "email_is_transactional": false
         *             }
         *           },
         *           "delay_in_minutes": 2
         *         }
         *       ],
         *       "filter": {
         *         "or": [
         *           {
         *             "and": [
         *               {
         *                 "type": "contacts_created_at_between",
         *                 "before": "2025-02-05T09:47:27.411Z",
         *                 "after": "2025-02-05T09:47:27.411Z"
         *               }
         *             ]
         *           }
         *         ]
         *       }
         *     } */
        CreateSequenceInput: {
            /** @default New Sequence */
            name: string;
            custom_id?: string;
            /** @default true */
            is_continuous: boolean;
            /**
             * ContactsCompositeFilter
             * @description A combination of contact filters. All filters within `and` arrays must apply to a contact in order for the contact to be included. On the other hand, only one of the filters within the `or` array must apply for the contact to be included. If no filter is provided, all contacts will be included.
             */
            filter: {
                or: {
                    and: components["schemas"]["ContactsFilter"][];
                }[];
            } | null;
            steps: {
                action: {
                    /** @enum {string} */
                    type: "send_emails";
                    data: {
                        from_email: string;
                        email_subject: string;
                        email_body: string;
                        email_sender_name: string;
                        email_is_transactional: boolean;
                    };
                } | {
                    /** @enum {string} */
                    type: "make_phone_calls";
                    data: {
                        aiPhoneAgentId: string;
                    };
                } | {
                    /** @enum {string} */
                    type: "send_sms_messages";
                    data: {
                        message: string;
                    };
                };
                delay_in_minutes?: number;
            }[];
        };
        CreateSequenceOutput: {
            /** Format: uuid */
            id: string;
        };
        EmailRecipient: {
            /** Format: email */
            to_email: string;
            /** @description Body of the email in HTML format. */
            email_body?: string;
            email_subject?: string;
            email_sender_name?: string;
            /** @description
             *     Whether the email is transactional. If set to `false`, Open will check if the
             *     contact has [unsubscribed/opted out](./unsubscribe_api) of receiving marketing
             *     emails before sending the email. Defaults to `true`. */
            email_is_transactional?: boolean;
        };
        FileUploadDto: {
            /** Format: binary */
            file: string;
        };
        GenericResponseDto: {
            data?: {
                success: boolean;
            };
            error?: {
                code: string;
                status: number;
                message: string;
            };
        };
        /** ChatSession */
        GetChatSessionOutput: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "open" | "closed_resolved" | "closed_unresolved";
            channel: {
                /**
                 * ChatSessionChannelType
                 * @enum {string}
                 */
                type: "web" | "email" | "phone_voice" | "slack" | "sms" | "whatsapp" | "api" | "web_voice";
            };
            contact?: components["schemas"]["Contact"];
            language?: string;
            assignee_id?: string;
            /** @description Present if the conversation was handed off to a human. */
            handoff?: {
                /**
                 * HandoffSentiment
                 * @enum {string}
                 */
                sentiment?: "angry" | "neutral" | "happy";
                summary: string;
            };
            /**
             * DateTime
             * Format: date-time
             * @description ISO 8601 date-time string
             */
            created_at: string | null;
            /**
             * DateTime
             * Format: date-time
             * @description ISO 8601 date-time string
             */
            updated_at: string | null;
        };
        GetSequenceOutput: {
            id: string;
            name: string;
            org_id: string;
            custom_id: string | null;
            /**
             * ContactsCompositeFilter
             * @description A combination of contact filters. All filters within `and` arrays must apply to a contact in order for the contact to be included. On the other hand, only one of the filters within the `or` array must apply for the contact to be included. If no filter is provided, all contacts will be included.
             */
            filter: {
                or: {
                    and: components["schemas"]["ContactsFilter"][];
                }[];
            } | null;
            steps: components["schemas"]["SequenceStep"][];
            is_continuous: boolean;
            started_at: string | null;
            canceled_at: string | null;
            ended_at: string | null;
            status: components["schemas"]["SequenceStatus"];
        };
        /** @description Paginated response. */
        ListChatHistoryOutput: {
            items: {
                /**
                 * DateTime
                 * Format: date-time
                 * @description ISO 8601 date-time string
                 */
                created_at: string | null;
                event: {
                    /** @enum {string} */
                    type: "message";
                    sender: components["schemas"]["ChatMessageSender"];
                    content: {
                        /** @enum {string} */
                        type: "text";
                        text: string;
                    };
                } | {
                    /** @enum {string} */
                    type: "handoff";
                    integration?: {
                        /** @enum {string} */
                        type: "zendesk";
                    };
                } | {
                    /** @enum {string} */
                    type: "ai_resolved_issue";
                } | {
                    /** @enum {string} */
                    type: "human_agent_comment";
                    human_agent_id: number;
                    content: {
                        /** @enum {string} */
                        type: "text";
                        text: string;
                    };
                } | {
                    /** @enum {string} */
                    type: "human_agent_joined";
                    human_agent_id: number;
                } | {
                    /** @enum {string} */
                    type: "human_agent_takeover";
                    human_agent_id: number;
                };
            }[];
            /** @description The `cursor` for the request to get the next set of items. Null if there is no more data. */
            next: string | null;
        };
        /** @description Paginated response. */
        ListChatSessionsOutput: {
            items: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                status: "open" | "closed_resolved" | "closed_unresolved";
                channel: {
                    /**
                     * ChatSessionChannelType
                     * @enum {string}
                     */
                    type: "web" | "email" | "phone_voice" | "slack" | "sms" | "whatsapp" | "api" | "web_voice";
                };
                contact?: components["schemas"]["Contact"];
                language?: string;
                assignee_id?: string;
                /** @description Present if the conversation was handed off to a human. */
                handoff?: {
                    /**
                     * HandoffSentiment
                     * @enum {string}
                     */
                    sentiment?: "angry" | "neutral" | "happy";
                    summary: string;
                };
                /**
                 * DateTime
                 * Format: date-time
                 * @description ISO 8601 date-time string
                 */
                created_at: string | null;
                /**
                 * DateTime
                 * Format: date-time
                 * @description ISO 8601 date-time string
                 */
                updated_at: string | null;
            }[];
            /** @description The `cursor` for the request to get the next set of items. Null if there is no more data. */
            next: string | null;
        };
        /** @description Paginated response. */
        ListContactsOutput: {
            items: components["schemas"]["Contact"][];
            /** @description The `cursor` for the request to get the next set of items. Null if there is no more data. */
            next: string | null;
        };
        /** @description Paginated response. */
        ListPhoneNumbersOutput: {
            items: {
                /** Format: uuid */
                id: string;
                name: string | null;
                phone_number: string | null;
            }[];
            /** @description The `cursor` for the request to get the next set of items. Null if there is no more data. */
            next: string | null;
        };
        PhoneAgentDto: {
            id: string;
            org_id: string;
            phone_number: string | null;
            name: string | null;
            /** @enum {string} */
            type: "inbound" | "outbound";
            language: string | null;
            accent: string | null;
            handoff_phone_number: string | null;
            interruptible: boolean;
            actionIds: string[] | null;
            instructions: string[] | null;
            data_collection_fields: string[] | null;
            data_collection_webhook_url: string | null;
            /** @enum {string} */
            model: "oppie-vox" | "oppie-vox-turbo" | "oppie-vox-2";
            voice_id: string | null;
            first_message: string | null;
            created_at: string;
            updated_at: string;
            provider_external_id: string | null;
            flow: {
                /** @enum {string} */
                type: "root" | "condition" | "action";
                content: string;
                children: {
                    /** @enum {string} */
                    type: "root" | "condition" | "action";
                    content: string;
                    children: {
                        /** @enum {string} */
                        type: "root" | "condition" | "action";
                        content: string;
                        children: unknown[];
                    }[];
                }[];
            } | null;
            use_org_knowledgebase: boolean;
        };
        SaveContactInput: {
            contact: components["schemas"]["ContactInput"];
        };
        SavecontactOutput: {
            /**
             * Format: uuid
             * @description The ID of the created contact.
             */
            id?: string;
        };
        SendEmailInput: {
            /**
             * Format: email
             * @description The email to send from. This email's domain name must be added and verified. Otherwise, the request will fail with a 400 status code.
             */
            from_email: string;
            /** @description
             *     Array of contacts to receive emails. The only required field is `to_email`, with the rest of the fields having fallback values that can be specified on the top level.
             *
             *     It's possible to repeat the same contact email in the array with different `delay_in_minutes` values to create a sequence of scheduled emails for that contact (e.g. for onboarding). */
            recipients: components["schemas"]["EmailRecipient"][];
            /** @description How much time (in minutes) to wait before sending the emails. */
            delay_in_minutes?: number;
            fallback_email_subject?: string;
            fallback_email_sender_name?: string;
            /** @description Fallback body of the email in HTML format. */
            fallback_email_body?: string;
        };
        /** @example {
         *       "sender": "contact",
         *       "message": {
         *         "type": "text",
         *         "text": "Hello!"
         *       }
         *     } */
        SendMessageInput: {
            /** @enum {string} */
            sender: "contact";
            /** @description Updated contact info */
            contact?: {
                name?: string;
                /** Format: email */
                email?: string;
                phone_number?: string;
                avatar_url?: string;
                custom_data?: {
                    [key: string]: string;
                };
            };
            message: {
                /** @enum {string} */
                type: "text";
                text: string;
                attachments?: {
                    id: string;
                    name: string;
                    size: number;
                    type: string;
                    url: string;
                }[];
            };
        };
        SendMessageOutput: {
            /** @enum {boolean} */
            success: true;
            code?: string | "session_assigned_to_human_agent";
            autopilotResponse?: {
                /** @enum {string} */
                type: "text";
                value: {
                    error: boolean;
                    content: string;
                };
                id?: string;
                mightSolveUserIssue: boolean;
            };
            uiResponse?: {
                /** @enum {string} */
                type: "ui";
                value: {
                    /** @enum {string} */
                    type: "ui_component";
                    request_response?: unknown;
                    name: string;
                    content?: string;
                };
                mightSolveUserIssue: boolean;
            };
            sessionIsHandedOff?: boolean;
        } | {
            /** @enum {boolean} */
            success: false;
            error: {
                code?: string;
                message?: string;
            };
        };
        /** @enum {string|null} */
        SequenceStatus: "pending" | "complete" | "canceled" | "active" | null;
        SequenceStep: {
            action: {
                /** @enum {string} */
                type: "send_emails";
                data: {
                    from_email: string;
                    email_subject: string;
                    email_body: string;
                    email_sender_name: string;
                    email_is_transactional: boolean;
                };
            } | {
                /** @enum {string} */
                type: "make_phone_calls";
                data: {
                    aiPhoneAgentId: string;
                };
            } | {
                /** @enum {string} */
                type: "send_sms_messages";
                data: {
                    message: string;
                };
            };
            delay_in_minutes?: number;
            started_at?: string;
            ended_at?: string;
        };
        StartOneOffSequenceOutputDto: {
            data?: {
                success: boolean;
            };
            error?: {
                /** @enum {string} */
                code: "sequence_not_found" | "one_off_sequence_is_canceled" | "sequence_already_started";
                status: 400 | 404;
                message: string;
            };
        };
        UpdateChatSessionInput: {
            /** @enum {string} */
            status?: "open" | "closed_resolved" | "closed_unresolved";
        };
        UpdateContactInput: {
            contact: components["schemas"]["ContactInput"];
        };
        UpdatePhoneAgentDto: {
            name?: string;
            /** @enum {string} */
            type?: "inbound" | "outbound";
            /** @description The language the AI phone agent should mainly speak in */
            language?: string | null;
            /** @description The accent the AI phone agent should mainly speak in */
            accent?: string | null;
            /** @description The phone number of the human agent to hand off the call to */
            handoff_phone_number?: string | null;
            /** @description Whether the agent can be interrupted or not */
            interruptible?: boolean;
            /** @description A list of action ids the AI phone agent has access to. A `null` value means all actions. An empty list means no actions */
            actionIds?: string[] | null;
            /** @description A list of instructions */
            instructions?: string[] | null;
            /** @description A list of fields to collect data about */
            data_collection_fields?: string[] | null;
            /** @description The webhook url to send the collected data to */
            data_collection_webhook_url?: string | null;
            /** @description The voice id */
            voice_id?: string | null;
            /** @description The first message the AI phone agent should say */
            first_message?: string | null;
            flow: {
                /** @enum {string} */
                type: "root" | "condition" | "action";
                content: string;
                children: {
                    /** @enum {string} */
                    type: "root" | "condition" | "action";
                    content: string;
                    children: {
                        /** @enum {string} */
                        type: "root" | "condition" | "action";
                        content: string;
                        children: unknown[];
                    }[];
                }[];
            } | null;
            /** @description Whether the AI phone agent should use the organization's knowledgebase (enabling it will increase the latency of the agent) */
            use_org_knowledgebase?: boolean | null;
        };
        /** @example {
         *       "name": "New name"
         *     } */
        UpdateSequenceInput: {
            /** @default New Sequence */
            name: string;
            custom_id?: string;
            /** @default true */
            is_continuous: boolean;
            /**
             * ContactsCompositeFilter
             * @description A combination of contact filters. All filters within `and` arrays must apply to a contact in order for the contact to be included. On the other hand, only one of the filters within the `or` array must apply for the contact to be included. If no filter is provided, all contacts will be included.
             */
            filter?: {
                or: {
                    and: components["schemas"]["ContactsFilter"][];
                }[];
            } | null;
            steps?: {
                action: {
                    /** @enum {string} */
                    type: "send_emails";
                    data: {
                        from_email: string;
                        email_subject: string;
                        email_body: string;
                        email_sender_name: string;
                        email_is_transactional: boolean;
                    };
                } | {
                    /** @enum {string} */
                    type: "make_phone_calls";
                    data: {
                        aiPhoneAgentId: string;
                    };
                } | {
                    /** @enum {string} */
                    type: "send_sms_messages";
                    data: {
                        message: string;
                    };
                };
                delay_in_minutes?: number;
            }[];
        };
        WidgetContactTokenResponseDto: {
            /** @description The JWT token to use for further requests */
            token: string;
        };
        ErrorDto: {
            statusCode?: number;
            message?: string;
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    importActionsFromOpenAapiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The OpenAPI (Swagger) file to import actions from. */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["FileUploadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    deleteAllActions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    listContacts: {
        parameters: {
            query?: {
                /** @description Pagination cursor to fetch the next set of results */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListContactsOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    saveContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveContactInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavecontactOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    deleteContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    updateContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContactInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    sendEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    listPhoneNumbers: {
        parameters: {
            query?: {
                /** @description Pagination cursor to fetch the next set of results */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPhoneNumbersOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    createPhoneAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhoneAgentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneAgentDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    deletePhoneNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phone_agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    updatePhoneAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phone_agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePhoneAgentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    listChatSessions: {
        parameters: {
            query?: {
                handed_off?: boolean;
                channel_type?: "web" | "email" | "phone_voice" | "slack" | "sms" | "whatsapp" | "api" | "web_voice";
                status?: "open" | "closed_resolved" | "closed_unresolved";
                /** @description Pagination cursor to fetch the next set of results */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListChatSessionsOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    createChatSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatSessionInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateChatSessionOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    getChatSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetChatSessionOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    updateChatSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChatSessionInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    listChatHistory: {
        parameters: {
            query?: {
                /** @description Pagination cursor to fetch the next set of results */
                cursor?: string;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListChatHistoryOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    createSequence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSequenceInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSequenceOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    getSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID or _custom ID_ for the sequence */
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSequenceOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    updateSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID or _custom ID_ for the sequence */
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSequenceInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    startSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID or _custom ID_ for the sequence */
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartOneOffSequenceOutputDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    cancelSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The sequence `id`. This can also be a run `id`. */
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    addContactsToSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID or _custom ID_ for the sequence. */
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddContactsToSequenceInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddContactsToSequenceOutput"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    authenticateWidgetUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthenticateUserPayloadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetContactTokenResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
}
